    try{
      log("1");
      throw SomethingHappened{ whatHappened := "an exception" };
      log("2");
      return "error";
    }
    catch(sh:SomethingHappened){
      return "ok " + sh.whatHappened;
    }